import '../styles/main.scss';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/global/Header';
import Logo from "../../public/img/logo.svg";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Devani Stageverslag',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="nl">
        <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <link rel="icon" type="image/x-icon" href="../../public/img/logo.svg" /> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;0,700;1,400&family=Open+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet" />
    </Head>
    <body>
        <Header />
        {children}
        <footer>
            <h1>Navigeren</h1>
            <ul>
                <li><Link href=""></Link></li>
            </ul>
            <Image
                src={Logo}
                width={114}
                height={25}
                alt="Devani logo"
            />
        </footer>
    </body>
    </html>
  );
}
